"""
Django settings for BugiNova project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_2xdj2ynsuidytrs)_2$_o09y2v(4o&)p7_ag-maek7w%0_5&f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'attachment_management',
    'bug_management',
    'comment_management',
    'notification_management',
    'project_management',
    'user_management',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BugiNova.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BugiNova.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASE_ROUTERS = ['BugiNova.database_router.AppDatabaseRouter']

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'buginova_default_db',
        'USER': 'postgres',
        'PASSWORD': '182002',
        'HOST': 'localhost',
        'PORT': '5432',
    },
    'attachment_management_db': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'attachment_management_db',
        'USER': 'postgres',
        'PASSWORD': '182002',
        'HOST': 'localhost',
        'PORT': '5432',
    },
    'bug_management_db': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'bug_management_db',
        'USER': 'postgres',
        'PASSWORD': '182002',
        'HOST': 'localhost',
        'PORT': '5432',
    },
    'comment_management_db': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'comment_management_db',
        'USER': 'postgres',
        'PASSWORD': '182002',
        'HOST': 'localhost',
        'PORT': '5432',
    },
    'notification_management_db': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'notification_management_db',
        'USER': 'postgres',
        'PASSWORD': '182002',
        'HOST': 'localhost',
    },
    'project_management_db': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'project_management_db',
        'USER': 'postgres',
        'PASSWORD': '182002',
        'HOST': 'localhost',
        'PORT': '5432',
    },
    'user_management_db': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'user_management_db',
        'USER': 'postgres',
        'PASSWORD': '182002',
        'HOST': 'localhost',
        'PORT': '5432',
    },
    
}


AUTH_USER_MODEL = 'user_management.UserModel'


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
